//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wuthering.WutheringCommentsPackage {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommentResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommentResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Wuthering.WutheringCommentsPackage.CommentResources", typeof(CommentResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;wuthering-comments&gt;
        ///	
        ///	&lt;author name=&quot;Ademar Letracteur&quot; initials=&quot;AL&quot; email=&quot;ademar.letracteur@gmail.com&quot; website=&quot;www.ademar-letracteur.com&quot;/&gt;
        ///
        ///	&lt;categories&gt;
        ///		&lt;category name=&quot;block&quot;		description=&quot;Thick block comment&quot;/&gt;
        ///		&lt;category name=&quot;class&quot;		description=&quot;Comment inserted before a class definition&quot;/&gt;
        ///		&lt;category name=&quot;code&quot;		description=&quot;Multiline comment inserted before a code block&quot;/&gt;
        ///		&lt;category name=&quot;file&quot;		description=&quot;Comment inserted at the top of a source file&quot;/&gt;
        ///		&lt;category name=&quot;func [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WutheringCommentsXml {
            get {
                return ResourceManager.GetString("WutheringCommentsXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;xs:schema attributeFormDefault=&quot;unqualified&quot; elementFormDefault=&quot;qualified&quot; 
        ///	   xmlns:xs=&quot;http://www.w3.org/2001/XMLSchema&quot;&gt;
        ///	&lt;xs:element name=&quot;wuthering-comments&quot;&gt;
        ///		&lt;xs:complexType&gt;
        ///			&lt;xs:sequence&gt;
        ///				&lt;xs:element name=&quot;author&quot;&gt;
        ///					&lt;xs:complexType&gt;
        ///						&lt;xs:attribute name=&quot;name&quot; type=&quot;xs:string&quot; use=&quot;required&quot; /&gt;
        ///						&lt;xs:attribute name=&quot;initials&quot; type=&quot;xs:string&quot; use=&quot;optional&quot; /&gt;
        ///						&lt;xs:attribute name=&quot;email&quot; type=&quot;xs:string&quot; use=&quot;optional&quot; /&gt;
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string WutheringCommentsXsd {
            get {
                return ResourceManager.GetString("WutheringCommentsXsd", resourceCulture);
            }
        }
    }
}
